### ISSUE TITLE
unable to get logging from broccoli-persistent-filter \w heimdall

### ISSUE THREAD

**Issue by stefanpenner** [heimdalljs/heimdalljs-logger#4]
steps to reproduce:
1. checkout: https://github.com/stefanpenner/broccoli-rollup/
2. `cd broccoli-rollup`
3. `npm install`
4. `DEBUG=broc* npm run build`
5. trigger a rebuild, no broccoli-persistent-filter/broccoli-babel-transpiler output?

**Comment by hjdivad** [comment]
@stefanpenner seems fine.

persistent-filter is using `debug`.  we can change those to `info`.

Are you able to reproduce with

```
DEBUG=broc* DEBUG_LEVEL=debug npm run build
```

**Comment by stefanpenner** [comment]
ah DEBUG_LEVEL, I believe the issue is then in persistent-filters usage, it should do some info logging.
