### ISSUE TITLE
Duplicate copies of `debug`

### ISSUE THREAD

**Issue by ef4** [heimdalljs/heimdalljs-logger#5]
This package rolls up its own copy of `debug` at build time. But it also has a runtime dependency on `debug`. This results in two copies being present, while only the rolled-up one is used.

This has ramifications for features like formatters, which are set on the `debug` module. As far as I can tell, it's not possible to install a custom formatter that is usable by heimdalljs-logger, because there's no way to get at the inner copy of `debug`.

**Comment by hjdivad** [comment]
Thanks for catching this @ef4.

**Comment by hjdivad** [comment]
published as v0.1.8

**Comment by ef4** [comment]
Nice!
